# Generated by Django 2.2.7 on 2020-01-04 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(unique=True)),
                ('id_gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('matricula', models.TextField(primary_key=True, serialize=False)),
                ('modelo', models.TextField()),
                ('marca', models.TextField()),
                ('consumo_km', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaInteligente',
            fields=[
                ('id_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('generado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2.Edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumosVehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumosEdificios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2.Edificio')),
            ],
        ),
    ]
