# Generated by Django 2.2.7 on 2020-01-04 12:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('matricula', models.TextField(primary_key=True, serialize=False)),
                ('modelo', models.TextField()),
                ('marca', models.TextField()),
                ('consumo_km', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaInteligente',
            fields=[
                ('id_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('generado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2.Edificio')),
            ],
        ),
        migrations.AddField(
            model_name='edificio',
            name='id_gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2.Empleado'),
        ),
        migrations.CreateModel(
            name='ConsumosVehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2.Empleado')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumosEdificios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2.Edificio')),
            ],
        ),
    ]
